=== markus008/xpilm019_ETE29E/xml/schema.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded" minOccurs="1"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:integer" name="id"/>
                <xs:element type="xs:string" name="first_name"/>
                <xs:element type="xs:string" name="last_name"/>
                <xs:element type="emailTyp" name="email"/>
                <xs:element type="genderTyp" name="gender"/>
                <xs:element type="xs:date" name="dob"/>
                <xs:element type="xs:string" name="city"/>
                <xs:element type="xs:string" name="company"/>
                <xs:element name="phone_numbers" type="phone_numbers_type"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="phone_numbers_type">
        <xs:sequence>
            <xs:element name="number" maxOccurs="unbounded" minOccurs="0"> </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="number">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:byte" name="id"/>
                <xs:element type="phoneTyp" name="phone"/>
                <xs:element type="typTyp" name="typ"/>
                <xs:element name="call_history" type="call_history_type"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="call_history_type">
        <xs:sequence>
            <xs:element name="call" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="call">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:date" name="date"/>
                <xs:element type="xs:string" name="time"/>
                <xs:element type="xs:string" name="call_length"/>
                <xs:element type="xs:int" name="to_number"/>
                <xs:element type="roamingTyp" name="roming"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="typTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="IOS"/>
            <xs:enumeration value="Android"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="genderTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Female"/>
            <xs:enumeration value="Male"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="roamingTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="phoneTyp">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*@.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    
</xs:schema>

=== markus008/xpilm019_ETE29E/xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" >
  <employee>
    <id>1</id>
    <first_name>Renata</first_name>
    <last_name>Mcwhinnie</last_name>
    <email>rmcwhinnie0@list-manage.com</email>
    <gender>Female</gender>
    <dob>1968-11-24</dob>
    <city>Guangshan Chengguanzhen</city>
    <company>Livepath</company>
    <phone_numbers>
      <number>
        <id>1</id>
        <phone>629266724</phone>
        <typ>IOS</typ>
        <call_history>
          <call>
            <date>2021-11-22</date>
            <time>3:59</time>
            <call_length>1:17</call_length>
            <to_number>644511511</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-06-02</date>
            <time>21:21</time>
            <call_length>2:06</call_length>
            <to_number>691781938</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2021-08-05</date>
            <time>4:42</time>
            <call_length>0:23</call_length>
            <to_number>703305696</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2021-07-02</date>
            <time>7:46</time>
            <call_length>0:09</call_length>
            <to_number>746889614</to_number>
            <roming>true</roming>
          </call>
        </call_history>
      </number>
      <number>
        <id>2</id>
        <phone>748102864</phone>
        <typ>Android</typ>
        <call_history>
          <call>
            <date>2021-10-20</date>
            <time>15:21</time>
            <call_length>0:43</call_length>
            <to_number>782351605</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2022-03-09</date>
            <time>8:49</time>
            <call_length>0:17</call_length>
            <to_number>793483997</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-07-13</date>
            <time>7:12</time>
            <call_length>0:20</call_length>
            <to_number>715517670</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-08-04</date>
            <time>2:02</time>
            <call_length>0:41</call_length>
            <to_number>743601632</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-05-16</date>
            <time>3:37</time>
            <call_length>0:26</call_length>
            <to_number>716210144</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2021-09-20</date>
            <time>2:07</time>
            <call_length>1:47</call_length>
            <to_number>711697310</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2021-05-04</date>
            <time>12:57</time>
            <call_length>0:04</call_length>
            <to_number>632216587</to_number>
            <roming>false</roming>
          </call>
        </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>2</id>
    <first_name>Nickie</first_name>
    <last_name>Dolton</last_name>
    <email>ndolton1@facebook.com</email>
    <gender>Female</gender>
    <dob>1971-12-10</dob>
    <city>Shangtang</city>
    <company>LiveZ</company>
    <phone_numbers>
      <number>
        <id>3</id>
        <phone>665499929</phone>
        <typ>IOS</typ>
        <call_history>
          <call>
            <date>2021-12-08</date>
            <time>7:48</time>
            <call_length>1:01</call_length>
            <to_number>643943011</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2022-02-26</date>
            <time>16:59</time>
            <call_length>2:06</call_length>
            <to_number>678610522</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-11-19</date>
            <time>16:31</time>
            <call_length>0:27</call_length>
            <to_number>732251741</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2022-03-01</date>
            <time>4:31</time>
            <call_length>1:26</call_length>
            <to_number>753444763</to_number>
            <roming>false</roming>
          </call>
        </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>3</id>
    <first_name>Weider</first_name>
    <last_name>Hempshall</last_name>
    <email>whempshall2@purevolume.com</email>
    <gender>Male</gender>
    <dob>1969-01-06</dob>
    <city>Croix</city>
    <company>Tagtune</company>
    <phone_numbers>
      <number>
        <id>4</id>
        <phone>724140097</phone>
        <typ>IOS</typ>
        <call_history>
          <call>
            <date>2021-06-04</date>
            <time>18:16</time>
            <call_length>0:06</call_length>
            <to_number>617328671</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-06-05</date>
            <time>3:31</time>
            <call_length>0:54</call_length>
            <to_number>687056591</to_number>
            <roming>false</roming>
          </call>
        </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>4</id>
    <first_name>Paulie</first_name>
    <last_name>Lago</last_name>
    <email>plago3@a8.net</email>
    <gender>Female</gender>
    <dob>1957-05-22</dob>
    <city>Semambung</city>
    <company>Gigaclub</company>
    <phone_numbers> </phone_numbers>
  </employee>
  <employee>
    <id>5</id>
    <first_name>Karee</first_name>
    <last_name>Jacqueme</last_name>
    <email>kjacqueme4@squarespace.com</email>
    <gender>Female</gender>
    <dob>1971-04-04</dob>
    <city>Gunungsari</city>
    <company>Devpulse</company>
    <phone_numbers>
      <number>
        <id>5</id>
        <phone>610350874</phone>
        <typ>IOS</typ>
        <call_history>
          <call>
            <date>2021-06-23</date>
            <time>15:52</time>
            <call_length>1:00</call_length>
            <to_number>701613159</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2022-04-25</date>
            <time>1:20</time>
            <call_length>0:14</call_length>
            <to_number>775322133</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-07-18</date>
            <time>11:42</time>
            <call_length>0:51</call_length>
            <to_number>707336180</to_number>
            <roming>false</roming>
          </call>
        </call_history>
      </number>
      <number>
        <id>6</id>
        <phone>678734172</phone>
        <typ>Android</typ>
        <call_history>
          <call>
            <date>2022-04-19</date>
            <time>20:45</time>
            <call_length>0:04</call_length>
            <to_number>752782429</to_number>
            <roming>true</roming>
          </call>
          <call>
            <date>2021-05-28</date>
            <time>14:59</time>
            <call_length>1:57</call_length>
            <to_number>683860834</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-05-29</date>
            <time>13:40</time>
            <call_length>0:09</call_length>
            <to_number>653836329</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-12-21</date>
            <time>2:10</time>
            <call_length>1:13</call_length>
            <to_number>796095211</to_number>
            <roming>false</roming>
          </call>
        </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>6</id>
    <first_name>Grete</first_name>
    <last_name>Mouget</last_name>
    <email>gmouget5@goodreads.com</email>
    <gender>Female</gender>
    <dob>1992-08-21</dob>
    <city>ZghartƒÅ</city>
    <company>Ooba</company>
    <phone_numbers> </phone_numbers>
  </employee>
  <employee>
    <id>7</id>
    <first_name>Wyatt</first_name>
    <last_name>Dearlove</last_name>
    <email>wdearlove6@chronoengine.com</email>
    <gender>Male</gender>
    <dob>1974-05-12</dob>
    <city>Waipawa</city>
    <company>Dazzlesphere</company>
    <phone_numbers>
      <number>
        <id>7</id>
        <phone>689823485</phone>
        <typ>IOS</typ>
        <call_history>
          <call>
            <date>2022-01-03</date>
            <time>22:06</time>
            <call_length>0:20</call_length>
            <to_number>731314896</to_number>
            <roming>false</roming>
          </call>
          <call>
            <date>2021-10-14</date>
            <time>20:59</time>
            <call_length>0:48</call_length>
            <to_number>633812205</to_number>
            <roming>true</roming>
          </call>
        </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>8</id>
    <first_name>Marthena</first_name>
    <last_name>Lavin</last_name>
    <email>mlavin7@ow.ly</email>
    <gender>Female</gender>
    <dob>1999-03-20</dob>
    <city>Kirs</city>
    <company>Mita</company>
    <phone_numbers>
      <number>
        <id>7</id>
        <phone>796179219</phone>
        <typ>Android</typ>
        <call_history> </call_history>
      </number>
    </phone_numbers>
  </employee>
  <employee>
    <id>9</id>
    <first_name>Cal</first_name>
    <last_name>Tremathick</last_name>
    <email>ctremathick8@cbsnews.com</email>
    <gender>Male</gender>
    <dob>1969-02-20</dob>
    <city>Itaquaquecetuba</city>
    <company>Ooba</company>
